package org.privatetracker.core.domain.model

private val UUID_PATTERN =
    Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

/** Canonical (lowercase) form of [raw], or null when it is not a UUID in 8-4-4-4-12 form. */
internal fun canonicalUuidOrNull(raw: String): String? =
    if (UUID_PATTERN.matches(raw)) raw.lowercase() else null

/** Identifies a tracker. The tracker generates it once and never changes it. */
@JvmInline
value class DeviceId private constructor(val value: String) {
    override fun toString(): String = value

    companion object {
        fun parse(raw: String): DeviceId? = canonicalUuidOrNull(raw)?.let(::DeviceId)
        fun of(raw: String): DeviceId = requireNotNull(parse(raw)) { "Not a UUID: $raw" }
    }
}

/** Identifies a location. The tracker generates it at capture time; it is the idempotency key. */
@JvmInline
value class LocationId private constructor(val value: String) {
    override fun toString(): String = value

    companion object {
        fun parse(raw: String): LocationId? = canonicalUuidOrNull(raw)?.let(::LocationId)
        fun of(raw: String): LocationId = requireNotNull(parse(raw)) { "Not a UUID: $raw" }
    }
}

/** Identifies a device session. Generated by the server. */
@JvmInline
value class SessionId private constructor(val value: String) {
    override fun toString(): String = value

    companion object {
        fun parse(raw: String): SessionId? = canonicalUuidOrNull(raw)?.let(::SessionId)
        fun of(raw: String): SessionId = requireNotNull(parse(raw)) { "Not a UUID: $raw" }
    }
}
