package org.privatetracker.tools.simulator

import java.nio.file.Files
import java.nio.file.Path
import java.sql.DriverManager

/** The locations a server holds for some devices. */
fun interface ServerSnapshot {
    fun locationsOf(deviceIds: Set<String>): List<LocationRecord>
}

/** Reads a copy of server.db pulled from the phone; tables and columns as in core:database. */
class SqliteServerSnapshot(private val dbFile: Path) : ServerSnapshot {
    override fun locationsOf(deviceIds: Set<String>): List<LocationRecord> {
        if (!Files.isRegularFile(dbFile)) throw UsageException("No existe la base $dbFile")
        if (deviceIds.isEmpty()) return emptyList()
        val placeholders = deviceIds.joinToString(",") { "?" }
        val sql = """
            SELECT d.device_uid, l.client_id, l.recorded_at, l.latitude, l.longitude
            FROM locations l JOIN devices d ON d.id = l.device_id
            WHERE d.device_uid IN ($placeholders)
        """.trimIndent()
        // Read-write on purpose: it is our copy, and SQLite needs to write to replay the WAL.
        DriverManager.getConnection("jdbc:sqlite:${dbFile.toAbsolutePath()}").use { connection ->
            val integrity = connection.createStatement().use { statement ->
                statement.executeQuery("PRAGMA quick_check").use { rows -> rows.next() && rows.getString(1) == "ok" }
            }
            if (!integrity) throw UsageException("La copia de server.db está dañada; cópiala de nuevo con el servidor detenido")
            connection.prepareStatement(sql).use { statement ->
                deviceIds.forEachIndexed { index, id -> statement.setString(index + 1, id) }
                statement.executeQuery().use { rows ->
                    return buildList {
                        while (rows.next()) {
                            add(
                                LocationRecord(
                                    key = LocationKey(rows.getString(1), rows.getString(2)),
                                    recordedAtMs = rows.getLong(3),
                                    latitude = rows.getDouble(4),
                                    longitude = rows.getDouble(5),
                                ),
                            )
                        }
                    }
                }
            }
        }
    }
}

/**
 * Every generated location in exactly one bucket. The run passes when it was closed properly, generated
 * something, and only [delivered] is non-empty.
 */
class VerificationReport(
    val devices: Int,
    val generated: Int,
    val delivered: Int,
    /** Null when the simulator did not close the run: it was killed or crashed. */
    val end: RunEnd?,
    /** The server acknowledged them, yet server.db does not have them: the one outcome that means a server bug. */
    val lost: List<LocationKey>,
    /** Never acknowledged: still queued when the run ended. */
    val undelivered: List<LocationKey>,
    /** Thrown away by a full outbox. */
    val dropped: List<LocationKey>,
    /** Location to the server's reason. */
    val rejected: Map<LocationKey, String>,
    /** Stored with a different time or coordinates than generated. */
    val altered: List<LocationKey>,
    /** In server.db under a simulated device, but never generated by this run. */
    val unexpected: List<LocationKey>,
    /** Stored more than once. The unique index on (device_id, client_id) should make this impossible. */
    val repeated: List<LocationKey>,
) {
    val noLosses: Boolean
        get() = lost.isEmpty() && undelivered.isEmpty() && dropped.isEmpty() && rejected.isEmpty() &&
            altered.isEmpty() && unexpected.isEmpty() && repeated.isEmpty()

    val passed: Boolean get() = noLosses && generated > 0 && end != null
}

object Verifier {
    fun verify(ledger: LedgerContents, snapshot: ServerSnapshot): VerificationReport {
        val rows = snapshot.locationsOf(ledger.devices.keys)
        val stored = rows.associateBy { it.key }
        var delivered = 0
        val lost = mutableListOf<LocationKey>()
        val undelivered = mutableListOf<LocationKey>()
        val dropped = mutableListOf<LocationKey>()
        val rejected = linkedMapOf<LocationKey, String>()
        val altered = mutableListOf<LocationKey>()

        for ((key, generated) in ledger.generated) {
            val row = stored[key]
            when {
                row != null -> if (row == generated) delivered++ else altered += key
                key in ledger.acknowledged -> lost += key
                key in ledger.rejected -> rejected[key] = ledger.rejected.getValue(key)
                key in ledger.dropped -> dropped += key
                else -> undelivered += key
            }
        }
        return VerificationReport(
            devices = ledger.devices.size,
            generated = ledger.generated.size,
            delivered = delivered,
            end = ledger.end,
            lost = lost,
            undelivered = undelivered,
            dropped = dropped,
            rejected = rejected,
            altered = altered,
            unexpected = (stored.keys - ledger.generated.keys).toList(),
            repeated = rows.groupingBy { it.key }.eachCount().filterValues { it > 1 }.keys.toList(),
        )
    }

    fun format(report: VerificationReport, examples: Int = 5): String = buildString {
        appendLine("Verificación contra server.db")
        appendLine("  Corrida:                  ${describe(report.end)}")
        appendLine("  Dispositivos simulados:   ${report.devices}")
        appendLine("  Generadas:                ${report.generated}")
        appendLine("  En server.db, intactas:   ${report.delivered}")
        bucket("Perdidas", "el servidor las confirmó pero no están en server.db", report.lost, examples)
        bucket("Sin entregar", "seguían en la cola al terminar", report.undelivered, examples)
        bucket("Descartadas", "la cola se llenó", report.dropped, examples)
        bucket("Rechazadas", "el servidor dijo que eran inválidas", report.rejected.map { it.key }, examples) { report.rejected.getValue(it) }
        bucket("Alteradas", "guardadas con otra hora o coordenadas", report.altered, examples)
        bucket("Inesperadas", "en server.db pero no en el ledger", report.unexpected, examples)
        bucket("Repetidas", "más de una fila en server.db", report.repeated, examples)
        appendLine()
        append(
            when {
                report.passed -> "Resultado: APROBADA. Cada posición generada está en server.db una vez y sin cambios."
                !report.noLosses -> "Resultado: NO APROBADA."
                report.generated == 0 -> "Resultado: NO APROBADA. El ledger no tiene posiciones."
                else -> "Resultado: INCOMPLETA. Lo registrado llegó completo, pero el simulador no cerró la corrida."
            },
        )
    }

    private fun describe(end: RunEnd?): String = when {
        end == null -> "sin cierre en el ledger (el simulador se interrumpió)"
        end.stoppedEarly -> "${formatDuration(end.elapsed)} (detenida a mano)"
        else -> formatDuration(end.elapsed)
    }

    private fun StringBuilder.bucket(
        label: String,
        meaning: String,
        keys: List<LocationKey>,
        examples: Int,
        detail: (LocationKey) -> String? = { null },
    ) {
        appendLine("  ${"$label:".padEnd(25)} ${keys.size}${if (keys.isEmpty()) "" else " ($meaning)"}")
        keys.take(examples).forEach { key ->
            appendLine("      ${key.deviceId} / ${key.locationId}${detail(key)?.let { " — $it" } ?: ""}")
        }
        if (keys.size > examples) appendLine("      … y ${keys.size - examples} más")
    }
}
